"""Type stubs for AppKit (PyObjC)"""
from typing import Any, Optional

class NSApplication: ...
class NSStatusBar: ...

class NSMenu:
    @staticmethod
    def alloc() -> 'NSMenu': ...
    def init(self) -> 'NSMenu': ...
    def setDelegate_(self, delegate: Any) -> None: ...
    def addItem_(self, item: Any) -> None: ...
    @staticmethod
    def separatorItem() -> Any: ...
    def setTitle_(self, title: str) -> None: ...

class NSMenuItem:
    @staticmethod
    def alloc() -> 'NSMenuItem': ...
    def init(self) -> 'NSMenuItem': ...
    def initWithTitle_action_keyEquivalent_(self, title: str, action: Optional[str], keyEquivalent: str) -> 'NSMenuItem': ...
    def setView_(self, view: Any) -> None: ...
    def setTarget_(self, target: Any) -> None: ...
    def setSubmenu_(self, menu: Any) -> None: ...
    def setRepresentedObject_(self, obj: Any) -> None: ...

class NSTextField:
    @staticmethod
    def alloc() -> 'NSTextField': ...
    def initWithFrame_(self, frame: Any) -> 'NSTextField': ...
    def setStringValue_(self, value: str) -> None: ...
    def stringValue(self) -> str: ...
    def setEditable_(self, editable: bool) -> None: ...
    def setSelectable_(self, selectable: bool) -> None: ...
    def setFont_(self, font: Any) -> None: ...
    def setBackgroundColor_(self, color: Any) -> None: ...
    def setTextColor_(self, color: Any) -> None: ...

class NSButton:
    @staticmethod
    def alloc() -> 'NSButton': ...
    def initWithFrame_(self, frame: Any) -> 'NSButton': ...
    def setTitle_(self, title: str) -> None: ...
    def setBezelStyle_(self, style: int) -> None: ...
    def setTarget_(self, target: Any) -> None: ...
    def setAction_(self, action: str) -> None: ...
    def setFont_(self, font: Any) -> None: ...
    def setEnabled_(self, enabled: bool) -> None: ...

class NSView:
    @staticmethod
    def alloc() -> 'NSView': ...
    def initWithFrame_(self, frame: Any) -> 'NSView': ...
    def addSubview_(self, view: Any) -> None: ...
    def setWantsLayer_(self, wants: bool) -> None: ...
    def layer(self) -> Any: ...
    def setFrame_(self, frame: Any) -> None: ...

class NSBox(NSView):
    """NSBox - Container view with border and title"""
    @staticmethod
    def alloc() -> 'NSBox': ...
    def initWithFrame_(self, frame: Any) -> 'NSBox': ...
    def setBoxType_(self, boxType: int) -> None: ...
    def setBorderType_(self, borderType: int) -> None: ...
    def setBorderWidth_(self, width: float) -> None: ...
    def setBorderColor_(self, color: Any) -> None: ...
    def setCornerRadius_(self, radius: float) -> None: ...
    def setFillColor_(self, color: Any) -> None: ...
    def setContentView_(self, view: Any) -> None: ...
    def setHidden_(self, hidden: bool) -> None: ...
    def setFrame_(self, frame: Any) -> None: ...

class NSColor: 
    @staticmethod
    def colorWithRed_green_blue_alpha_(r: float, g: float, b: float, a: float) -> 'NSColor': ...
    @staticmethod
    def whiteColor() -> 'NSColor': ...
    @staticmethod
    def blackColor() -> 'NSColor': ...

class NSFont:
    @staticmethod
    def systemFontOfSize_(size: float) -> 'NSFont': ...
    @staticmethod
    def monospacedSystemFontOfSize_weight_(size: float, weight: float) -> 'NSFont': ...
    @staticmethod
    def fontWithName_size_(name: str, size: float) -> 'NSFont': ...

class NSNotificationCenter: ...
class NSUserNotification: ...
class NSUserNotificationCenter: ...

class NSTextView:
    @staticmethod
    def alloc() -> 'NSTextView': ...
    def initWithFrame_(self, frame: Any) -> 'NSTextView': ...
    def setEditable_(self, editable: bool) -> None: ...
    def setSelectable_(self, selectable: bool) -> None: ...
    def setRichText_(self, rich: bool) -> None: ...
    def setFont_(self, font: Any) -> None: ...
    def setBackgroundColor_(self, color: Any) -> None: ...
    def setTextColor_(self, color: Any) -> None: ...
    def setInsertionPointColor_(self, color: Any) -> None: ...
    def setInsertionPointWidth_(self, width: float) -> None: ...
    def setString_(self, text: str) -> None: ...
    def string(self) -> str: ...
    def selectedRange(self) -> Any: ...
    def setSelectedRange_(self, range: tuple) -> None: ...
    def insertText_(self, text: str) -> None: ...
    def isEditable(self) -> bool: ...
    def setWantsLayer_(self, wants: bool) -> None: ...
    def layer(self) -> Any: ...
    def setAllowsUndo_(self, allows: bool) -> None: ...
    def setUsesFindBar_(self, uses: bool) -> None: ...
    def setUsesFontPanel_(self, uses: bool) -> None: ...
    def setUsesLigatures_(self, uses: bool) -> None: ...
    def setImportsGraphics_(self, imports: bool) -> None: ...
    def setAutomaticTextReplacementEnabled_(self, enabled: bool) -> None: ...
    def setAutomaticQuoteSubstitutionEnabled_(self, enabled: bool) -> None: ...
    def setAutomaticDashSubstitutionEnabled_(self, enabled: bool) -> None: ...
    def setAutomaticSpellingCorrectionEnabled_(self, enabled: bool) -> None: ...
    def setGrammarCheckingEnabled_(self, enabled: bool) -> None: ...
    def setAutomaticTextCompletionEnabled_(self, enabled: bool) -> None: ...
    def setAutomaticLinkDetectionEnabled_(self, enabled: bool) -> None: ...
    def setDrawsBackground_(self, draws: bool) -> None: ...
    def setVerticallyResizable_(self, resizable: bool) -> None: ...
    def setHorizontallyResizable_(self, resizable: bool) -> None: ...
    def textContainer(self) -> Any: ...
    def textStorage(self) -> Any: ...
    def setTextContainerInset_(self, inset: Any) -> None: ...
    def window(self) -> Any: ...
    def becomeFirstResponder(self) -> bool: ...
    def acceptsFirstResponder(self) -> bool: ...
    def copy_(self, sender: Any) -> bool: ...
    def paste_(self, sender: Any) -> bool: ...
    def cut_(self, sender: Any) -> bool: ...
    def selectAll_(self, sender: Any) -> bool: ...
    def delete_(self, sender: Any) -> None: ...
    def performKeyEquivalent_(self, event: Any) -> bool: ...
    def validateUserInterfaceItem_(self, item: Any) -> bool: ...
    def shouldChangeTextInRange_replacementString_(self, range: tuple, text: str) -> bool: ...
    def replaceCharactersInRange_withString_(self, range: tuple, text: str) -> None: ...
    def didChangeText(self) -> None: ...
    def keyDown_(self, event: Any) -> None: ...

class NSScrollView:
    @staticmethod
    def alloc() -> 'NSScrollView': ...
    def initWithFrame_(self, frame: Any) -> 'NSScrollView': ...
    def setDocumentView_(self, view: Any) -> None: ...
    def setHasVerticalScroller_(self, has: bool) -> None: ...
    def setHasHorizontalScroller_(self, has: bool) -> None: ...
    def setAutohidesScrollers_(self, hides: bool) -> None: ...
    def setHidden_(self, hidden: bool) -> None: ...
    def setBorderType_(self, borderType: int) -> None: ...
    def setDrawsBackground_(self, draws: bool) -> None: ...
    def setBackgroundColor_(self, color: Any) -> None: ...
    def setScrollerStyle_(self, style: int) -> None: ...
    def setVerticalScrollElasticity_(self, elasticity: int) -> None: ...
    def setAutoresizingMask_(self, mask: int) -> None: ...

class NSPasteboard:
    @staticmethod
    def generalPasteboard() -> 'NSPasteboard': ...
    def clearContents(self) -> None: ...
    def setString_forType_(self, string: str, type: str) -> bool: ...
    def stringForType_(self, type: str) -> Optional[str]: ...
    def changeCount(self) -> int: ...
    def types(self) -> Any: ...
    def dataForType_(self, type: str) -> Any: ...
    def setData_forType_(self, data: Any, type: str) -> bool: ...

class NSWorkspace:
    """NSWorkspace - Manage running applications and system operations"""
    @staticmethod
    def sharedWorkspace() -> 'NSWorkspace': ...
    def runningApplications(self) -> Any: ...
    def activeApplication(self) -> Any: ...
    def launchApplication_(self, appName: str) -> bool: ...
    def openFile_(self, path: str) -> bool: ...
    def openURL_(self, url: Any) -> bool: ...

NSApp: Any
