"""Type stubs for AppKit (PyObjC)"""
from typing import Any, Optional

class NSApplication: ...
class NSStatusBar: ...
class NSMenu: ...
class NSMenuItem: ...
class NSTextField: ...
class NSButton: ...
class NSView: ...
class NSColor: 
    @staticmethod
    def colorWithRed_green_blue_alpha_(r: float, g: float, b: float, a: float) -> 'NSColor': ...
    @staticmethod
    def whiteColor() -> 'NSColor': ...
    @staticmethod
    def blackColor() -> 'NSColor': ...

class NSFont:
    @staticmethod
    def systemFontOfSize_(size: float) -> 'NSFont': ...

class NSNotificationCenter: ...
class NSUserNotification: ...
class NSUserNotificationCenter: ...

class NSTextView:
    def setEditable_(self, editable: bool) -> None: ...
    def setSelectable_(self, selectable: bool) -> None: ...
    def setRichText_(self, rich: bool) -> None: ...
    def setFont_(self, font: Any) -> None: ...
    def setBackgroundColor_(self, color: Any) -> None: ...
    def setTextColor_(self, color: Any) -> None: ...
    def setInsertionPointColor_(self, color: Any) -> None: ...
    def setString_(self, text: str) -> None: ...
    def string(self) -> str: ...
    def selectedRange(self) -> Any: ...
    def setSelectedRange_(self, range: tuple) -> None: ...
    def insertText_(self, text: str) -> None: ...
    def isEditable(self) -> bool: ...
    def setWantsLayer_(self, wants: bool) -> None: ...
    def layer(self) -> Any: ...
    def setAllowsUndo_(self, allows: bool) -> None: ...
    def setUsesFindBar_(self, uses: bool) -> None: ...
    def setAutomaticTextReplacementEnabled_(self, enabled: bool) -> None: ...
    def setAutomaticQuoteSubstitutionEnabled_(self, enabled: bool) -> None: ...
    def setAutomaticDashSubstitutionEnabled_(self, enabled: bool) -> None: ...

class NSScrollView:
    def setDocumentView_(self, view: Any) -> None: ...
    def setHasVerticalScroller_(self, has: bool) -> None: ...
    def setHasHorizontalScroller_(self, has: bool) -> None: ...
    def setAutohidesScrollers_(self, hides: bool) -> None: ...
    def setHidden_(self, hidden: bool) -> None: ...

class NSPasteboard:
    @staticmethod
    def generalPasteboard() -> 'NSPasteboard': ...
    def clearContents(self) -> None: ...
    def setString_forType_(self, string: str, type: str) -> bool: ...
    def stringForType_(self, type: str) -> Optional[str]: ...

NSApp: Any
