"""Type stubs for Foundation (PyObjC)"""
from typing import Any

class NSObject:
    def init(self) -> Any: ...
    def performSelectorOnMainThread_withObject_waitUntilDone_(self, selector: str, obj: Any, wait: bool) -> None: ...

def NSMakeRect(x: float, y: float, w: float, h: float) -> Any: ...
def NSMakeSize(w: float, h: float) -> Any: ...
